[package]
name = "ports-info"
version = "0.1.0"
edition = "2021"
authors = ["mFat"]
license = "GPL-3.0"
description = "Ports Info - Listening Ports Information"

[dependencies]
gtk4 = "0.9"
libadwaita = "0.7.1"
sysinfo = "0.29"
chrono = "0.4"

[build-dependencies]
glib-build-tools = "0.18"
